name: Publish Docker image
env:
  DOCKERHUB_REPOSITORY: carlsmig/village-green
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare variables
        id: prep
        run: |
          DOCKER_IMAGE="${{ env.DOCKERHUB_REPOSITORY }}"
          BRANCH="$(git symbolic-ref --short HEAD)"
          SHA="$(git rev-parse --short=10 HEAD)"
          DESCRIBE="$(git describe --tags)"
          TAG="$(git describe --tags --abbrev=0)"
          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:sha-${SHA}"
          {
            echo "sha=${SHA}"
            echo "tag=${TAG}"
            echo "branch=${BRANCH}"
            echo "tags=${TAGS}"
            echo "describe=${DESCRIBE}"
            echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          } >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          build-args: |
            COMMIT_BRANCH=${{ steps.prep.outputs.branch }}
            COMMIT_SHA=${{ steps.prep.outputs.sha }}
            COMMIT_TAG=${{ steps.prep.outputs.tag }}
            COMMIT_DESCRIBE=${{ steps.prep.outputs.describe }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.title=village-green
            org.opencontainers.image.description=Village Green API and Web client
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.prep.outputs.tag }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ steps.prep.outputs.describe }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
